### ISSUE TITLE
Can't connect to Skype via email or phone instead of Skype username

### ISSUE THREAD

**Issue by MurzNN** [matrix-hacks/matrix-puppet-skype#14]
I have new Skype account, that have no normal skype login, so I can login to it in web.skype.com only via email or phone. Skype support answer that this is normal and all new accounts will can connect only via email/phone. 

But I can't configure matrix-puppet-skype to login via email (I type email in `username` key of config.json), after `node index.js` it shows error: 
```
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
starting matrix client
Got push rules
synced
starting skype client
{ MicrosoftAccountLogin: Unable to login with MicrosoftAccount.
  caused by GetLiveToken: Unable to get the Live token for Skype
  caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\"Refresh\" content=\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033\"/></noscript><title>Continue</title><script type=\"text/javascript\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\"javascript:DoSubmit();\"><form name=\"fmHF\" id=\"fmHF\" action=\"https://account.live.com/identity/confirm?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d0%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d8F3FE4061C9B2069&mkt=EN-US&uiflavor=web&id=293290&uaid=ae72fccf7556dec95ab2b682a4ecf9ca\" method=\"post\" target=\"_top\"><input type=\"hidden\" name=\"ipt\" id=\"ipt\" value=\"Dc0*npb07VftnRz0ctc0JeZ!kvwzwrZ8hgc!ghjipgsrsSdCzNvX8QNXbyif4d5k3Q0eKcL29VV1doG4*jeyqzzEIraBiNzRY*D5x3tO4*zJyLK6wj8!WUUlgXkTRXKRl4xY6zbd1eR!K6Squ*RWcn4MvxtAvp7NiNWNCh4vt9yFaW!9tqnBPygMBdgVCburkjcLrPPh3NffuLIzBtDZwXntC9deKVF!VbAAUI7D!i7q!NLldARtUrtMzo23nAVvSVkhdgO!qTlSSvsekJIJ*AzvwiXIf3t0TsPQvNBOzCUuwfhTCXTMFTrEhEu7p8AovmM!o1lO7PbI7x23ovjY9lCUb8e!5HnrCY3sT1cDx2lqixLo!s!gaXbgojcDVwUPwk!dG8AK83wLtfOyknxDFaDPfHZRd3Y3f1!0apXGLYR0!zrNysUm5MNOx1s3z7SZGYcQbYXmHk!apihhkacTpD2wXgyj7YxssGQTQ5NXyx7F\"></form></body></html>"
    at Object.create (node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)
    at scrapLiveToken (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)
    at node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'MicrosoftAccountLogin',
  data: {},
  cause: 
   { GetLiveToken: Unable to get the Live token for Skype
     caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\"Refresh\" content=\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033\"/></noscript><title>Continue</title><script type=\"text/javascript\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\"javascript:DoSubmit();\"><form name=\"fmHF\" id=\"fmHF\" action=\"https://account.live.com/identity/confirm?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d0%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d8F3FE4061C9B2069&mkt=EN-US&uiflavor=web&id=293290&uaid=ae72fccf7556dec95ab2b682a4ecf9ca\" method=\"post\" target=\"_top\"><input type=\"hidden\" name=\"ipt\" id=\"ipt\" value=\"Dc0*npb07VftnRz0ctc0JeZ!kvwzwrZ8hgc!ghjipgsrsSdCzNvX8QNXbyif4d5k3Q0eKcL29VV1doG4*jeyqzzEIraBiNzRY*D5x3tO4*zJyLK6wj8!WUUlgXkTRXKRl4xY6zbd1eR!K6Squ*RWcn4MvxtAvp7NiNWNCh4vt9yFaW!9tqnBPygMBdgVCburkjcLrPPh3NffuLIzBtDZwXntC9deKVF!VbAAUI7D!i7q!NLldARtUrtMzo23nAVvSVkhdgO!qTlSSvsekJIJ*AzvwiXIf3t0TsPQvNBOzCUuwfhTCXTMFTrEhEu7p8AovmM!o1lO7PbI7x23ovjY9lCUb8e!5HnrCY3sT1cDx2lqixLo!s!gaXbgojcDVwUPwk!dG8AK83wLtfOyknxDFaDPfHZRd3Y3f1!0apXGLYR0!zrNysUm5MNOx1s3z7SZGYcQbYXmHk!apihhkacTpD2wXgyj7YxssGQTQ5NXyx7F\"></form></body></html>"
       at Object.create (node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)
       at scrapLiveToken (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)
       at node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20
       at Generator.next (<anonymous>)
       at fulfilled (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     name: 'GetLiveToken',
     data: {},
     cause: 
      { LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\"Refresh\" content=\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033\"/></noscript><title>Continue</title><script type=\"text/javascript\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\"javascript:DoSubmit();\"><form name=\"fmHF\" id=\"fmHF\" action=\"https://account.live.com/identity/confirm?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d0%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d8F3FE4061C9B2069&mkt=EN-US&uiflavor=web&id=293290&uaid=ae72fccf7556dec95ab2b682a4ecf9ca\" method=\"post\" target=\"_top\"><input type=\"hidden\" name=\"ipt\" id=\"ipt\" value=\"Dc0*npb07VftnRz0ctc0JeZ!kvwzwrZ8hgc!ghjipgsrsSdCzNvX8QNXbyif4d5k3Q0eKcL29VV1doG4*jeyqzzEIraBiNzRY*D5x3tO4*zJyLK6wj8!WUUlgXkTRXKRl4xY6zbd1eR!K6Squ*RWcn4MvxtAvp7NiNWNCh4vt9yFaW!9tqnBPygMBdgVCburkjcLrPPh3NffuLIzBtDZwXntC9deKVF!VbAAUI7D!i7q!NLldARtUrtMzo23nAVvSVkhdgO!qTlSSvsekJIJ*AzvwiXIf3t0TsPQvNBOzCUuwfhTCXTMFTrEhEu7p8AovmM!o1lO7PbI7x23ovjY9lCUb8e!5HnrCY3sT1cDx2lqixLo!s!gaXbgojcDVwUPwk!dG8AK83wLtfOyknxDFaDPfHZRd3Y3f1!0apXGLYR0!zrNysUm5MNOx1s3z7SZGYcQbYXmHk!apihhkacTpD2wXgyj7YxssGQTQ5NXyx7F\"></form></body></html>"
          at Object.create (node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)
          at scrapLiveToken (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)
          at node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20
          at Generator.next (<anonymous>)
          at fulfilled (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
        name: 'LiveTokenNotFound',
        data: [Object],
        message: 'LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\\"Refresh\\" content=\\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033\\"/></noscript><title>Continue</title><script type=\\"text/javascript\\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\\"javascript:DoSubmit();\\"><form name=\\"fmHF\\" id=\\"fmHF\\" action=\\"https://account.live.com/identity/confirm?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d0%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d8F3FE4061C9B2069&mkt=EN-US&uiflavor=web&id=293290&uaid=ae72fccf7556dec95ab2b682a4ecf9ca\\" method=\\"post\\" target=\\"_top\\"><input type=\\"hidden\\" name=\\"ipt\\" id=\\"ipt\\" value=\\"Dc0*npb07VftnRz0ctc0JeZ!kvwzwrZ8hgc!ghjipgsrsSdCzNvX8QNXbyif4d5k3Q0eKcL29VV1doG4*jeyqzzEIraBiNzRY*D5x3tO4*zJyLK6wj8!WUUlgXkTRXKRl4xY6zbd1eR!K6Squ*RWcn4MvxtAvp7NiNWNCh4vt9yFaW!9tqnBPygMBdgVCburkjcLrPPh3NffuLIzBtDZwXntC9deKVF!VbAAUI7D!i7q!NLldARtUrtMzo23nAVvSVkhdgO!qTlSSvsekJIJ*AzvwiXIf3t0TsPQvNBOzCUuwfhTCXTMFTrEhEu7p8AovmM!o1lO7PbI7x23ovjY9lCUb8e!5HnrCY3sT1cDx2lqixLo!s!gaXbgojcDVwUPwk!dG8AK83wLtfOyknxDFaDPfHZRd3Y3f1!0apXGLYR0!zrNysUm5MNOx1s3z7SZGYcQbYXmHk!apihhkacTpD2wXgyj7YxssGQTQ5NXyx7F\\"></form></body></html>"\n    at Object.create (node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)\n    at scrapLiveToken (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)\n    at node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20\n    at Generator.next (<anonymous>)\n    at fulfilled (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' },
     message: 'GetLiveToken: Unable to get the Live token for Skype\n  caused by LiveTokenNotFound: Unable to find the Live token. This token is normally found in the HTML response as the value of the element with the id "t". This error may be caused by a change in the Microsoft login workflow. HTML page: "<html><head><noscript>JavaScript required to sign in<meta http-equiv=\\"Refresh\\" content=\\"0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033\\"/></noscript><title>Continue</title><script type=\\"text/javascript\\">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload=\\"javascript:DoSubmit();\\"><form name=\\"fmHF\\" id=\\"fmHF\\" action=\\"https://account.live.com/identity/confirm?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d0%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d8F3FE4061C9B2069&mkt=EN-US&uiflavor=web&id=293290&uaid=ae72fccf7556dec95ab2b682a4ecf9ca\\" method=\\"post\\" target=\\"_top\\"><input type=\\"hidden\\" name=\\"ipt\\" id=\\"ipt\\" value=\\"Dc0*npb07VftnRz0ctc0JeZ!kvwzwrZ8hgc!ghjipgsrsSdCzNvX8QNXbyif4d5k3Q0eKcL29VV1doG4*jeyqzzEIraBiNzRY*D5x3tO4*zJyLK6wj8!WUUlgXkTRXKRl4xY6zbd1eR!K6Squ*RWcn4MvxtAvp7NiNWNCh4vt9yFaW!9tqnBPygMBdgVCburkjcLrPPh3NffuLIzBtDZwXntC9deKVF!VbAAUI7D!i7q!NLldARtUrtMzo23nAVvSVkhdgO!qTlSSvsekJIJ*AzvwiXIf3t0TsPQvNBOzCUuwfhTCXTMFTrEhEu7p8AovmM!o1lO7PbI7x23ovjY9lCUb8e!5HnrCY3sT1cDx2lqixLo!s!gaXbgojcDVwUPwk!dG8AK83wLtfOyknxDFaDPfHZRd3Y3f1!0apXGLYR0!zrNysUm5MNOx1s3z7SZGYcQbYXmHk!apihhkacTpD2wXgyj7YxssGQTQ5NXyx7F\\"></form></body></html>"\n    at Object.create (node_modules/skype-http/dist/lib-es2015/lib/errors/microsoft-account/get-live-token.js:17:16)\n    at scrapLiveToken (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:218:61)\n    at node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:137:20\n    at Generator.next (<anonymous>)\n    at fulfilled (node_modules/skype-http/dist/lib-es2015/lib/providers/microsoft-account.js:4:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' } }
```
Also I try to type phone, and replace `username` to `email` in `config.json` but this isn't help.

Did matrix-puppet-skype support logging in via email or phone instead of skype login/username?

**Comment by demurgos** [comment]
@grigori-gru
This is fixed in the upcoming version of `skype-http`. You can install it now with `npm install -S skype-http@next`.

**Comment by grigori-gru** [comment]
Thanks! But we use 0.0.14 and email logging in our config and it works well.

**Comment by demurgos** [comment]
Well, to be fair you are right that [it was fixed in 0.0.14](https://github.com/ocilo/skype-http/blob/master/CHANGELOG.md#0014-2018-01-12) but the `next` version has some fixes for the contacts API that makes it more stable (I recommend to already use it). (`Do not throw on unexpected extra keys when reading responses.`)
