### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by w1r0x** [matrix-hacks/matrix-puppet-skype#19]
Error appears when somebody write to the room that was created before bridge service started

```
Error in handleThirdPartyRoomMessage { TypeError: Cannot read property 'match' of undefined
    at deskypeify (/app/skypeify.js:22:15)
    at client.getConversation.then (/app/index.js:144:17)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
  [stack]: 'TypeError: Cannot read property \'match\' of undefined\n    at deskypeify (/app/skypeify.js:22:15)\n    at client.getConversation.then (/app/index.js:144:17)\n    at \n    at process._tickCallback (internal/process/next_tick.js:188:7)',
  [message]: 'Cannot read property \'match\' of undefined' } { roomId: 'MTk6NjBkNzRiN2JjN2UyNGVjOGJhM2QxZmI1YzY0ZTcwZDhAdGhyZWFkLnNreXBl',
  senderId: 'ODpuaWthc255Yzk0',
  senderName: 'Nikita Soshenko',
  avatarUrl: 'https://avatar.skype.com/v1/avatars/nikasnyc94?auth_key=-488367919',
  text: 'Всем привет.\r\nС нашей стороны партнёрка под Казахстан и механизм распознавания партнёрки по присылаемой валюте были реализованы изначально. Так что ждём вас и по идее мы готовы :)' } ﻿
```

**Comment by nr23730** [comment]
This is an issue with matrix-puppet-bridge that has been resolved.
