### ISSUE TITLE
Error "data is not defined" on incoming Skype messages

### ISSUE THREAD

**Issue by MurzNN** [matrix-hacks/matrix-puppet-skype#9]
Sometimes I have lost Skype messages in Matrix server, and bridge shows those error:
```
{ poll: An error happened while processing the polled messages
  caused by ReferenceError: data is not defined
    at App.getThirdPartyUserDataById_noPromise ([path]/matrix-puppet-skype/index.js:87:16)
    at App.getPayload ([path]/matrix-puppet-skype/index.js:103:35)
    at App.handleSkypeMessage ([path]/matrix-puppet-skype/index.js:109:24)
    at Client.client.on ([path]/matrix-puppet-skype/index.js:44:12)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at Api.api.on ([path]/matrix-puppet-skype/client.js:53:22)
    at emitOne (events.js:115:13)
    at Api.emit (events.js:210:7)
    at Api.handlePollingEvent ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:83:14)
    at MessagesPoller.Api.messagesPoller.on ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:30:62)
    at emitOne (events.js:115:13)
    at MessagesPoller.emit (events.js:210:7)
    at MessagesPoller. ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:312:34)
    at Generator.next ()
    at fulfilled ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:4:58)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'poll',
  [_message]: 'An error happened while processing the polled messages',
  data: {},
  cause: 
   { ReferenceError: data is not defined
       at App.getThirdPartyUserDataById_noPromise ([path]/matrix-puppet-skype/index.js:87:16)
       at App.getPayload ([path]/matrix-puppet-skype/index.js:103:35)
       at App.handleSkypeMessage ([path]/matrix-puppet-skype/index.js:109:24)
       at Client.client.on ([path]/matrix-puppet-skype/index.js:44:12)
       at emitOne (events.js:115:13)
       at Client.emit (events.js:210:7)
       at Api.api.on ([path]/matrix-puppet-skype/client.js:53:22)
       at emitOne (events.js:115:13)
       at Api.emit (events.js:210:7)
       at Api.handlePollingEvent ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:83:14)
       at MessagesPoller.Api.messagesPoller.on ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:30:62)
       at emitOne (events.js:115:13)
       at MessagesPoller.emit (events.js:210:7)
       at MessagesPoller. ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:312:34)
       at Generator.next ()
       at fulfilled ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:4:58)
       at 
       at process._tickCallback (internal/process/next_tick.js:188:7)
     [stack]: 'ReferenceError: data is not defined\n    at App.getThirdPartyUserDataById_noPromise ([path]/matrix-puppet-skype/index.js:87:16)\n    at App.getPayload ([path]/matrix-puppet-skype/index.js:103:35)\n    at App.handleSkypeMessage ([path]/matrix-puppet-skype/index.js:109:24)\n    at Client.client.on ([path]/matrix-puppet-skype/index.js:44:12)\n    at emitOne (events.js:115:13)\n    at Client.emit (events.js:210:7)\n    at Api.api.on ([path]/matrix-puppet-skype/client.js:53:22)\n    at emitOne (events.js:115:13)\n    at Api.emit (events.js:210:7)\n    at Api.handlePollingEvent ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:83:14)\n    at MessagesPoller.Api.messagesPoller.on ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:30:62)\n    at emitOne (events.js:115:13)\n    at MessagesPoller.emit (events.js:210:7)\n    at MessagesPoller. ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:312:34)\n    at Generator.next ()\n    at fulfilled ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:4:58)\n    at \n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     [message]: 'data is not defined' },
  [_stack]: 'poll: An error happened while processing the polled messages\n  caused by ReferenceError: data is not defined\n    at App.getThirdPartyUserDataById_noPromise ([path]/matrix-puppet-skype/index.js:87:16)\n    at App.getPayload ([path]/matrix-puppet-skype/index.js:103:35)\n    at App.handleSkypeMessage ([path]/matrix-puppet-skype/index.js:109:24)\n    at Client.client.on ([path]/matrix-puppet-skype/index.js:44:12)\n    at emitOne (events.js:115:13)\n    at Client.emit (events.js:210:7)\n    at Api.api.on ([path]/matrix-puppet-skype/client.js:53:22)\n    at emitOne (events.js:115:13)\n    at Api.emit (events.js:210:7)\n    at Api.handlePollingEvent ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:83:14)\n    at MessagesPoller.Api.messagesPoller.on ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:30:62)\n    at emitOne (events.js:115:13)\n    at MessagesPoller.emit (events.js:210:7)\n    at MessagesPoller. ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:312:34)\n    at Generator.next ()\n    at fulfilled ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:4:58)\n    at \n    at process._tickCallback (internal/process/next_tick.js:188:7)',
  [_stackContainer]: undefined,
  message: 'poll: An error happened while processing the polled messages\n  caused by ReferenceError: data is not defined\n    at App.getThirdPartyUserDataById_noPromise ([path]/matrix-puppet-skype/index.js:87:16)\n    at App.getPayload ([path]/matrix-puppet-skype/index.js:103:35)\n    at App.handleSkypeMessage ([path]/matrix-puppet-skype/index.js:109:24)\n    at Client.client.on ([path]/matrix-puppet-skype/index.js:44:12)\n    at emitOne (events.js:115:13)\n    at Client.emit (events.js:210:7)\n    at Api.api.on ([path]/matrix-puppet-skype/client.js:53:22)\n    at emitOne (events.js:115:13)\n    at Api.emit (events.js:210:7)\n    at Api.handlePollingEvent ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:83:14)\n    at MessagesPoller.Api.messagesPoller.on ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/api.js:30:62)\n    at emitOne (events.js:115:13)\n    at MessagesPoller.emit (events.js:210:7)\n    at MessagesPoller. ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:312:34)\n    at Generator.next ()\n    at fulfilled ([path]/matrix-puppet-skype/node_modules/skype-http/dist/lib-es2015/lib/polling/messages-poller.js:4:58)\n    at \n    at process._tickCallback (internal/process/next_tick.js:188:7)' } ﻿
```

Message text is:
```
Доброго утра!
Я вернулся из отпуска. Если есть вопросы какие по проекту, готов ответить
```

**Comment by Sorunome** [comment]
May be related to https://github.com/ocilo/skype-http/issues/51

**Comment by MurzNN** [comment]
This error repeats even after full restart of service and reconnect, so seems not related to memory leak problems.
